import Container from 'react-bootstrap/Container';
export default function About() {
    return (
    <>
    <h1 className='justify-text-left border-bottom p-2 m-1'>&gt;about</h1>
    <Container className="text-light p-2 w-70">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec. Mattis enim ut tellus elementum sagittis vitae et leo duis. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Risus pretium quam vulputate dignissim suspendisse in est. Consectetur adipiscing elit duis tristique sollicitudin. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Massa id neque aliquam vestibulum. Interdum velit euismod in pellentesque massa placerat. Quis enim lobortis scelerisque fermentum dui faucibus in ornare quam. Proin libero nunc consequat interdum varius sit. Sapien faucibus et molestie ac. Tortor dignissim convallis aenean et tortor at risus. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Quam vulputate dignissim suspendisse in est ante in nibh. Maecenas accumsan lacus vel facilisis volutpat est velit. Lectus nulla at volutpat diam. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Velit laoreet id donec ultrices tincidunt arcu non. Id volutpat lacus laoreet non curabitur.

        Scelerisque eu ultrices vitae auctor eu. Ultrices vitae auctor eu augue ut lectus arcu. Blandit massa enim nec dui. Pretium viverra suspendisse potenti nullam ac tortor. Mattis aliquam faucibus purus in massa. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. At auctor urna nunc id cursus. Et molestie ac feugiat sed. Nunc faucibus a pellentesque sit. Ut diam quam nulla porttitor massa id neque. Vulputate mi sit amet mauris commodo quis imperdiet. Aliquam eleifend mi in nulla posuere sollicitudin. Tincidunt augue interdum velit euismod in pellentesque. Leo a diam sollicitudin tempor. Tincidunt augue interdum velit euismod in pellentesque.
        
        Feugiat in ante metus dictum at tempor commodo ullamcorper a. Bibendum arcu vitae elementum curabitur vitae. Quam adipiscing vitae proin sagittis. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Bibendum at varius vel pharetra vel turpis. Dolor sit amet consectetur adipiscing elit. Sem nulla pharetra diam sit amet nisl suscipit adipiscing. Nunc id cursus metus aliquam. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Tempus iaculis urna id volutpat lacus laoreet non. Nisi scelerisque eu ultrices vitae auctor.
        
        Volutpat odio facilisis mauris sit amet massa vitae. Amet risus nullam eget felis eget nunc lobortis. Vel turpis nunc eget lorem. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Massa sapien faucibus et molestie ac feugiat sed lectus vestibulum. Sit amet venenatis urna cursus eget nunc scelerisque. Vulputate mi sit amet mauris commodo. Libero id faucibus nisl tincidunt eget nullam non nisi. Eros donec ac odio tempor. Morbi quis commodo odio aenean sed adipiscing diam. Lectus urna duis convallis convallis tellus id interdum velit laoreet.
        
        Tincidunt ornare massa eget egestas purus viverra. Tempor orci dapibus ultrices in iaculis nunc. Varius duis at consectetur lorem donec. Nisl rhoncus mattis rhoncus urna neque. Quisque sagittis purus sit amet volutpat consequat mauris nunc congue. Blandit massa enim nec dui nunc mattis enim ut. Ac felis donec et odio pellentesque diam volutpat. In tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Mattis pellentesque id nibh tortor id. Mi sit amet mauris commodo quis imperdiet massa tincidunt nunc. Elementum pulvinar etiam non quam lacus suspendisse faucibus. Sagittis vitae et leo duis ut diam. Posuere lorem ipsum dolor sit amet consectetur adipiscing. Lectus vestibulum mattis ullamcorper velit sed ullamcorper.
        
        Enim eu turpis egestas pretium aenean pharetra. Elit pellentesque habitant morbi tristique senectus et netus. Est ullamcorper eget nulla facilisi etiam. Lorem ipsum dolor sit amet consectetur. Nibh sit amet commodo nulla facilisi nullam. Blandit aliquam etiam erat velit scelerisque in dictum non. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Posuere lorem ipsum dolor sit amet consectetur adipiscing elit duis. Sit amet cursus sit amet dictum sit. Augue eget arcu dictum varius. Amet porttitor eget dolor morbi. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Malesuada pellentesque elit eget gravida cum sociis.
        
        Ipsum dolor sit amet consectetur adipiscing elit duis tristique. Velit aliquet sagittis id consectetur purus ut faucibus. Malesuada fames ac turpis egestas integer. Blandit volutpat maecenas volutpat blandit. Magna fringilla urna porttitor rhoncus dolor purus non enim. Quis viverra nibh cras pulvinar mattis nunc sed blandit libero. Elementum nisi quis eleifend quam. Faucibus purus in massa tempor. Metus aliquam eleifend mi in. Leo vel fringilla est ullamcorper eget nulla facilisi. Adipiscing commodo elit at imperdiet dui accumsan sit. Iaculis nunc sed augue lacus viverra vitae congue. Vulputate ut pharetra sit amet aliquam id diam maecenas. Lobortis feugiat vivamus at augue eget arcu dictum. Purus gravida quis blandit turpis cursus in hac habitasse platea. Nunc faucibus a pellentesque sit. Libero id faucibus nisl tincidunt eget nullam non. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. At ultrices mi tempus imperdiet nulla.</Container>
        </>
        );

}